[font]
size = 13
normal.family = "Jetbrains Mono"
normal.style = "Regular"
bold.family = "Jetbrains Mono"
bold.style = "Bold"
italic.family = "Jetbrains Mono"
italic.style = "Italic"
offset.y = -2

[env]
TERM = "xterm-256color"

#[shell]
#program="tmux"

[colors]
draw_bold_text_with_bright_colors = true

[window]
#decorations = "None"
decorations_theme_variant="Dark"
startup_mode="Maximized"
padding.x =10
padding.y = 10


# Gnome (Gnome Terminal Default)

# Primary colors
[colors.primary]
background = '#0d0d1b'
foreground = '#ccccce'

# Colors used for 'custom_cursor_colors'
[colors.cursor]
text = '#bbbbbb'
cursor = '#ff0017'

# Colors 0 through 7
[colors.normal]
black = '#282828'
red = '#ca1444'
green = '#789aba'
yellow = '#b3879f'
blue = '#95569b'
magenta = '#cb6fa1'
cyan = '#fb6e93'
white = '#cf98c1'

# Colors 8 through 15
[colors.bright]
black = '#98218e'
red = '#cb515d'
green = '#5a87b1'
yellow = '#9c61ab'
blue = '#9a77b1'
magenta = '#f2a297'
cyan = '#f4436f'
white = '#ebdbb2'
