[font]
size = 13
normal.family = "Jetbrains Mono"
normal.style = "Regular"
bold.family = "Jetbrains Mono"
bold.style = "Bold"
italic.family = "Jetbrains Mono"
italic.style = "Italic"
offset.y = -2

[env]
TERM = "xterm-256color"

#[shell]
#program="tmux"

[colors]
draw_bold_text_with_bright_colors = true

[window]
#decorations = "None"
decorations_theme_variant="Dark"
startup_mode="Maximized"
padding.x =10
padding.y = 10

# Colours (Monokai Charcoal)

# Default Colours
[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

# Normal Colours
[colors.normal]
black   = '#1a1a1a'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#fa8419'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#c4c5b5'

# Bright Colours
[colors.bright]
black   = '#625e4c'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#e0d561'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#f6f6ef'


## Gnome (Gnome Terminal Default)
#
## Default colors
#[colors.primary]
#background = '#1e1e1e'
#foreground = '#ffffff'
#
## Normal colors
#[colors.normal]
#black      = '#171421'
#red        = '#c01c28'
#green      = '#26a269'
#yellow     = '#a2734c'
#blue       = '#12488b'
#magenta    = '#a347ba'
#cyan       = '#2aa1b3'
#white      = '#d0cfcc'
#
## Bright colors
#[colors.bright]
#black      = '#5e5c64'
#red        = '#f66151'
#green      = '#33d17a'
#yellow     = '#e9ad0c'
#blue       = '#2a7bde'
#magenta    = '#c061cb'
#cyan       = '#33c7de'
#white      = '#ffffff'
