[font]
size = 12
normal.family = "Adwaita Mono"
normal.style = "Regular"
bold.family = "Adwaita Mono"
bold.style = "Bold"
italic.family = "Adwaita Mono"
italic.style = "Italic"
offset.y = -1

[env]
# Not needed whilst our default setup is tmux-256color instead
# TERM = "xterm-256color"

#[shell]
#program="tmux"

[colors]
draw_bold_text_with_bright_colors = true

[window]
decorations_theme_variant="Dark"
startup_mode="Maximized"
padding.x = 2
padding.y = 0

[selection]
save_to_clipboard = true

[terminal]
osc52 = "OnlyCopy"



# Darkblue Alacritty Theme
# Based on the Vim darkblue color scheme

[colors.primary]
background = "#000040"  # ogDeepBlue - main background
foreground = "#c0c0c0"  # ogLightGrey - main text
dim_foreground = "#808080"  # ogGrey - dimmed text
bright_foreground = "#ffffff"  # white - bright text

[colors.cursor]
text = "#000000"  # black
cursor = "#ffff60"  # ogYellow - cursor color

[colors.vi_mode_cursor]
text = "#000040"  # ogDeepBlue
cursor = "#90fff0"  # ogCyan - vi mode cursor

[colors.search.matches]
foreground = "#ffffff"  # white
background = "#0030ff"  # ogBlue - search matches

[colors.search.focused_match]
foreground = "#000000"  # black
background = "#90fff0"  # ogCyan - focused search match

[colors.footer_bar]
foreground = "#000040"  # ogDeepBlue
background = "#c0c0c0"  # ogLightGrey

[colors.hints.start]
foreground = "#000000"  # black
background = "#ffff60"  # ogYellow

[colors.hints.end]
foreground = "#ffffff"  # white
background = "#0030ff"  # ogBlue

[colors.selection]
text = "#ffffff"  # white
background = "#8080ff"  # ogViolet - visual selection

[colors.normal]
black = "#000000"    # black
red = "#8b0000"      # ogDarkerRed
green = "#90f020"    # ogGreen
yellow = "#ffa500"   # ogOrange
blue = "#0030ff"     # ogBlue
magenta = "#8b008b"  # ogDarkMag
cyan = "#008b8b"     # ogDarkCyan
white = "#c0c0c0"    # ogLightGrey

[colors.bright]
black = "#808080"    # ogGrey
red = "#ffa0a0"      # ogLightRed
green = "#90f020"    # ogGreen (bright)
yellow = "#ffff60"   # ogYellow
blue = "#80a0ff"     # ogLightViolet
magenta = "#ff00ff"  # ogMagenta
cyan = "#90fff0"     # ogCyan
white = "#ffffff"    # white

# Additional indexed colors for extended compatibility
[[colors.indexed_colors]]
index = 16
color = "#ffa500"  # ogOrange

[[colors.indexed_colors]]
index = 17
color = "#ff80ff"  # ogLightMag


