Match User *
    ForceCommand if [ -n "$SSH_ORIGINAL_COMMAND" ]; then eval "$SSH_ORIGINAL_COMMAND"; else exec systemd-inhibit --who="SSH session" --why="Active ssh user blocks suspend" --what=sleep:idle --mode=block bash; fi
